- cortex_complete: # Set default model if one is not specified by user in Cortex Copmlete tool
  - default_model: snowflake-llama-3.3-70b
- search_services: # List all Cortex Search services
  - service_name: SEC_SEARCH_SERVICE
    description: > # Should start with "Search service that ..."
      Search services that contains reports that publicly traded US companies
      must file with the Securities and Exchange Commission (SEC)
    database_name: CUBE_TESTING
    schema_name: PUBLIC
  - service_name: FOMC_MINUTES_SEARCH_SERVICE
    description: >
      Search service that contains the minutes of regularly scheduled
      meetings held by The Federal Open Market Committee
    database_name: DEMO_CORTEX_SEARCH
    schema_name: FOMC
- analyst_services: # List all Cortex Analsyt semantic models/views
  - service_name: CUSTOMER_DATA # Create descriptive name for the service
    semantic_model: '@CATRANSLATOR.ANALYTICS.DATA/customers.yaml' # Fully-qualify semantic YAML model or Semantic View
    description: > # Should start with "Analyst service that ..."
      Analyst service that contains structured customer data to query
